feat(ci): added executables verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,9 @@ name: epitech coding style
 on:
   push:
 
+env:
+  EXECUTABLES: "zappy_server,zappy_ai,zappy_gui"
+
 jobs:
   server_coding_style:
     runs-on: ubuntu-latest
@@ -21,8 +24,24 @@ jobs:
               error_code=$(echo "$line" | cut -d: -f4)
               type=$(echo "$line" | cut -d: -f3 | cut -d- -f4)
               has_errors=true
-              echo "Error ${type}:${error_code} in ${path} at line ${line_number}"
+              echo "::error title=${type}:${error_code} in ${path} at line ${line_number}::"
           done < coding-style-reports.log
           if $has_errors; then
               exit 1
           fi
+  check_exexecutables:
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Execute the project with make cmd
+        run: |
+          make
+          SPLIT_EXECUTABLES=$(echo $EXECUTABLES | tr "," "\n")
+          for EXECUTABLE in $SPLIT_EXECUTABLES; do
+            if [[ ! -f $EXECUTABLE ]]; then
+            echo "::error title=This executable was not found $EXECUTABLE::"
+            exit 1
+          fi
+          done
